apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: search-service
  namespace: observability
  labels:
    release: monitoring
spec:
  selector:
    matchLabels:
      app: search-service
      prometheus: scrape
  namespaceSelector:
    matchNames:
      - platform
  endpoints:
    - port: http
      path: /metrics
      interval: 15s
