apiVersion: apps/v1
kind: Deployment
metadata:
  name: ai-sre-agent
  namespace: platform
  labels:
    app: ai-sre-agent
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ai-sre-agent
  template:
    metadata:
      labels:
        app: ai-sre-agent
    spec:
      containers:
        - name: ai-sre-agent
          image: ghcr.io/franklindot04/ai-sre-agent:v1.0.14
          imagePullPolicy: Always
          ports:
            - containerPort: 3005
          readinessProbe:
            httpGet:
              path: /health
              port: 3005
            initialDelaySeconds: 5
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /health
              port: 3005
            initialDelaySeconds: 10
            periodSeconds: 20
          resources:
            requests:
              cpu: "100m"
              memory: "128Mi"
            limits:
              cpu: "500m"
              memory: "512Mi"
          env:
            - name: SLACK_WEBHOOK_URL
              valueFrom:
                secretKeyRef:
                  name: ai-sre-slack
                  key: webhook_url
